FROM continuumio/anaconda3

COPY project_tool/API/project_tags .

ARG AWS_DYNAMODB_URL
ARG AWS_DEFAULT_REGION
ARG ENV_TAGGING_API_BASE_URL
ARG ENV_BASE_URL

ARG ENV_AUTH0_URL
ARG ENV_AUTH0_AUDIENCE
ARG ENV_AUTH0_CLIENT_ID
ARG ENV_AUTH0_CLIENT_SECRET
ARG ENV_AUTH0_PROXY_SERVER_URL

ARG ENV_BUSAPI_URL

ENV AWS_DYNAMODB_URL=$AWS_DYNAMODB_URL
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

ENV ENV_TAGGING_API_BASE_URL=$ENV_TAGGING_API_BASE_URL
ENV ENV_BASE_URL=$ENV_BASE_URL

ENV ENV_SOLUTION_DB_COLLECTION "project_details"
ENV ENV_SOLUTION_TAGGING_CONFIG_PATH "tagging_config.json"
ENV ENV_SOLUTION_SKIP_SKILLS_PATH "skip_skill_list.txt"

ENV ENV_TAGGING_TAGGING_EMSI_TYPE "internal_no_refresh"
ENV ENV_TAGGING_ENABLE_CUSTOM_TAGGING "False"
ENV ENV_TAGGING_UPDATE_LOCAL_BEFORE_TAGGING "False"
ENV ENV_TAGGING_EXTRACT_CONFIDENCE "False"
ENV ENV_TAGGING_TEXT_LENGTH "300"
ENV ENV_EMSI_CLIENT_ID "o7lhw1fzerq20tdj"
ENV ENV_EMSI_CLIENT_SECRET "heE4erYg"
ENV ENV_EMSI_SCOPE "emsi_open"

ENV ENV_AUTH0_URL=$ENV_AUTH0_URL
ENV ENV_AUTH0_AUDIENCE=$ENV_AUTH0_AUDIENCE
ENV ENV_AUTH0_CLIENT_ID=$ENV_AUTH0_CLIENT_ID
ENV ENV_AUTH0_CLIENT_SECRET=$ENV_AUTH0_CLIENT_SECRET
ENV ENV_AUTH0_PROXY_SERVER_URL=$ENV_AUTH0_PROXY_SERVER_URL

ENV ENV_TOKEN_CACHE_TIME 4000

ENV ENV_BUSAPI_URL=$ENV_BUSAPI_URL
ENV ENV_KAFKA_ERROR_TOPIC "common.error.reporting"

RUN conda config --add channels conda-forge

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN pip install dateparser

COPY bus-api-wrapper-python /bus-api-wrapper-python

RUN pip install -e bus-api-wrapper-python

CMD python -u ./manage.py runserver --noreload 0.0.0.0:27
